# Generated by Django 4.1 on 2022-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=256)),
                ('movielink', models.CharField(max_length=2000)),
                ('imagelink', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
