# Generated by Django 4.1 on 2022-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='movielink',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
