# Generated by Django 4.1 on 2022-11-22 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_moviedata_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='imagelink',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
