# Generated by Django 4.1 on 2022-12-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_movie_moviedata_moviename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('moviename', models.CharField(max_length=256)),
                ('movielink', models.CharField(blank=True, max_length=2000, null=True)),
                ('imagelink', models.CharField(blank=True, max_length=2000, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieData',
        ),
    ]
