# Generated by Django 4.1 on 2022-12-06 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_alter_movies_username_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('moviename', models.CharField(max_length=256, unique=True)),
                ('movielink', models.CharField(blank=True, max_length=2000, null=True)),
                ('imagelink', models.CharField(blank=True, max_length=2000, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
