# Generated by Django 4.1 on 2022-12-17 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_usermovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='user_moviename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.movie'),
        ),
    ]
