# Generated by Django 4.1 on 2022-12-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_usermovie_user_moviename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='user_moviename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movie'),
        ),
    ]
